### ISSUE TITLE
helm 模板文件语法错误

### ISSUE THREAD

**Issue by Hello-Linux** [gocrane/crane-scheduler#15]
helm chart中的templates/scheduler-deployment.yaml 语法错误，if格式修复如下
```
containers:
      - command:
        - /scheduler
        - --leader-elect=false
        - --config=/etc/kubernetes/kube-scheduler/scheduler-config.yaml
        {{- if ge .Capabilities.KubeVersion.Minor "22" }}
        image: "{{ .Values.scheduler.image.repository }}:0.0.23"
        {{- else }}
        image: "{{ .Values.scheduler.image.repository }}:0.0.20"
        {{- end }}
```
