### ISSUE TITLE
代替原始调度器失败

### ISSUE THREAD

**Issue by zhimushan** [gocrane/crane-scheduler#42]
你好，请问下“Modify configfile of kube-scheduler(`scheduler-config.yaml`) to enable Dynamic scheduler plugin and configure plugin args:”这一步具体是怎么操作的，我没有在原始的调度器中找到scheduler-config.yaml这个文件，如果直接用crane-scheduler的deploy/dynamic里的scheduler-config.yaml，就会出现如下错误：
`[root@master dynamic]# kubectl apply -f scheduler-config.yaml `
`error: unable to recognize "scheduler-config.yaml": no matches for kind "KubeSchedulerConfiguration" in version "kubescheduler.config.k8s.io/v1beta2"   `
`[root@master dynamic]# vim scheduler-config.yaml  `
`[root@master dynamic]# kubectl apply -f scheduler-config.yaml  `
`error: unable to recognize "scheduler-config.yaml": no matches for kind "KubeSchedulerConfiguration" in version "kubescheduler.config.k8s.io/v1beta1"`

kube-scheduler-master的报错
`Events:`
`  Type     Reason   Age              From     Message`
 ` ----     ------   ----             ----     -------`
`  Normal   Pulling  41s              kubelet  Pulling image "docker.io/gocrane/crane-scheduler:0.0.20"`
`  Normal   Pulled   7s               kubelet  Successfully pulled image "docker.io/gocrane/crane-scheduler:0.0.20" in 33.793503977s`
`  Normal   Created  6s (x2 over 7s)  kubelet  Created container kube-scheduler`
`  Warning  Failed   6s (x2 over 7s)  kubelet  Error: failed to start container "kube-scheduler": Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "kube-scheduler": executable file not found in $PATH: unknown`
`  Normal   Pulled   6s               kubelet  Container image "docker.io/gocrane/crane-scheduler:0.0.20" already present on machine`
`  Warning  BackOff  1s (x2 over 1s)  kubelet  Back-off restarting failed container`

如果作为crane第二调度器则可以正常使用

**Comment by xieydd** [comment]
you can update KubeSchedulerCofiguration manually, this command have some error
`KUBE_EDITOR="sed -i 's/v1beta2/v1beta1/g'" kubectl edit cm scheduler-config -n crane-system`
i wil fixed it.

**Comment by zhimushan** [comment]
我可以问下我的kube-scheduler.yaml这个文件修改正确吗？主要修改了四个部分
```
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    - --port=0
    - --config=/etc/kubernetes/scheduler-config.yaml
```
```
    image: gocrane/crane-scheduler:0.0.23
```
```
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /etc/kubernetes/scheduler-config.yaml
      name: schedulerconfig
      readOnly: true
```
```
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /etc/kubernetes/scheduler-config.yaml
      type: FileOrCreate
    name: schedulerconfig
```
主要就是安装里的第二步我不太会操作，麻烦了
